DeveloperOrg/src/objects/Interviewer__c.object
<CustomObject>
    <description>Interviewer to interview the candidate</description>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Interviewers</relationshipLabel>
        <relationshipName>Interviewers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DeveloperOrg/src/objects/Position__c.object
<CustomObject>
    <description>Available Positions in the Company</description>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/src/classes/Reparenting_Demo.cls
public class Reparenting_Demo{
    public void reparenting() {
        Interviewer__c inter = [select id, Position__c, Position__r.Name from Interviewer__c limit 1];
        System.debug('Interviewer - ' + inter);
        List<Position__c> pos = [Select id, Name from Position__c];
        System.debug('Position - ' + Pos);
        Id MgrPosId;
        Id TechPosId;
        for(Position__c p:pos) {
        	if(p.Name == 'Manager') {
        		MgrPosId = P.Id;
        	} else if(p.Name == 'Technology Analyst') {
        		TechPosId = p.Id;
        	}
        }
        
        if(inter.Position__r.Name == 'Manager') {
        	inter.Position__c = TechPosId;
        } else if(inter.Position__r.Name == 'Technology Analyst') {
        	inter.Position__c = MgrPosId;
        }
        
        update inter;
    }
}